In [2]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


In [3]:
df = pd.read_csv("train.csv", header=None, delimiter = ',')
trainD = np.array(df)
print(trainD.shape)

(20000, 785)


In [4]:
trainX = trainD[:,:(trainD.shape[1] - 1)]
trainY = trainD[:,(trainD.shape[1]-1)]

print(trainX.shape)
print(trainY.shape)

(20000, 784)
(20000,)


In [7]:
train0 = trainD[trainD[:,-1] == 0]
train1 = trainD[trainD[:,-1] == 1]
train2 = trainD[trainD[:,-1] == 2]
train3 = trainD[trainD[:,-1] == 3]
train4 = trainD[trainD[:,-1] == 4]
train5 = trainD[trainD[:,-1] == 5]
train6 = trainD[trainD[:,-1] == 6]
train7 = trainD[trainD[:,-1] == 7]
train8 = trainD[trainD[:,-1] == 8]
train9 = trainD[trainD[:,-1] == 9]
# print(train6[0:10,:])




[[0 0 0 ... 0 0 6]
 [0 0 0 ... 0 0 6]
 [0 0 0 ... 0 0 6]
 ...
 [0 0 0 ... 0 0 6]
 [0 0 0 ... 0 0 6]
 [0 0 0 ... 0 0 6]]


In [73]:
# this class is of binary classification
class SVMbin():
    def __init__(self, x, iterations=100, lambda1 = 1):
        X=x
        self.iterations = iterations
        self.lambda1 = lambda1
        # here, Xb contains the 784 columns of X, and the final column is 1, for the bias term
        self.Xb = np.ones((X.shape[0],X.shape[1]))
        self.Xb[:,:-1] = X[:,:-1]
        # uniq contains the 2 unique values of X[:,-1]
        self.uniq = np.unique(X[:,-1])
                
        def f(x):
            if x == self.uniq[0]:
                return 1
            else: return -1
        
        self.Y = np.array([f(xi) for xi in X[:,-1]])

        
        # print(self.Y[-50:-1])
        self.w = np.zeros((1,self.Xb.shape[1]))
        
        
    
    # assuming the final column contains the labels
    # this function will train w of dimension 1,785
    def train(self,k):
       
        for i in range(1,self.iterations+1):
            indices = np.random.random_integers(self.Xb.shape[0]-1,size=(k,1))
            
            # tempPlusX = np.empty(shape=(1,self.Xb.shape[1]),dtype=int)
            # tempPlusY = np.empty(shape=(1,1),dtype=int)
            # 
            sum = np.zeros((1,self.Xb.shape[1]))
            for j in indices:
                y = self.Y[j]
                x = self.Xb[j,:]
                if (y*(np.dot(x,self.w.T))) <1:
                    sum += y*x
                    # tempPlusX = np.vstack((tempPlusX,x))
                    # tempPlusY = np.vstack((tempPlusY,y))
            
            eta = 1/(self.lambda1 * i)
            self.w = (1-eta*self.lambda1)*self.w + (eta/k)*sum
            
        # return w
    
    #     assuming X is of dimensions (:,785)
    def predict(self,X):
        temp = np.ones((X.shape[0],X.shape[1]))
        temp[:,:-1] = X[:,:-1]
        
        def helper(t):
            td = np.dot(t,self.w.T)
            if td>0: 
                return self.uniq[0]
            else: return self.uniq[1]
        # helpervec = np.vectorize(helper())
        
        # y = helpervec(temp)
        # return y
        return np.array([helper(xi) for xi in temp])

In [75]:
def accuracyCalc(actual,pred):
    sum=0
    for i in range(actual.shape[0]):
        if actual[i]==pred[i]:
            sum+=1
    return (sum/actual.shape[0])

In [76]:
# data01 = np.vstack((train1,train2))
# # data01 = trainD[(trainD[:,-1] == 2)||(trainD[:,-1] == 1)]
# # print(data01[-1,:])
# trial = SVMbin(x=data01)
# trial.train(k=30)
# # print(data01[0:50,-1])
# temptrail = data01[:,:]
# 
# print(temptrail.shape)
# print(temptrail[:,-1])
# 
# predictions = trial.predict(temptrail)
# actuals = temptrail[:,-1]
# 
# print(accuracyCalc(actuals,predictions))


(4000, 785)
[1 1 1 ... 2 2 2]
0.99175
None


/home/somani/anaconda3/envs/MLRG1/lib/python3.5/site-packages/ipykernel_launcher.py:31: DeprecationWarning: This function is deprecated. Please call randint(1, 3999 + 1) instead
