In [1]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


In [2]:
df = pd.read_csv("train.csv", header=None, delimiter = ',')
trainD = np.array(df)
print(trainD.shape)

(20000, 785)


In [3]:
trainX = trainD[:,:(trainD.shape[1] - 1)]
trainY = trainD[:,(trainD.shape[1]-1)]

print(trainX.shape)
print(trainY.shape)


(20000, 784)
(20000,)


In [18]:
class SVM():
    def __init__(self, iter=100, lambda1 = 1):
        self.iter = iter
        self.lambda1 = lambda1
        
    
    # assuming the final column contains the labels
    def train(self,X,k):
        Xb = np.ones((X.shape[0],X.shape[1]+1))
        Xb[:,1:] = X
        uniq = np.unique(Xb[:,-1])
        
        def f(x):
            if x == uniq[0]:
                return 1
            else: return -1
        
        #changing labels to +1 and -1
        Xb[:,-1] = np.array([f(xi) for xi in Xb[:,-1]])
        
        
#       the first column becomes the bias layer of ones
        w = np.zeros((1,Xb.shape[1]-1))
        for i in range(self.iter):
            np.random.shuffle(Xb)
            # temp has the first k rows of the data
            temp = Xb[:k,:]
            
            # tempPlus will have all those with y<w,x> < 1
            tempPlus = np.empty(shape=(1,Xb.shape[1]),dtype=int)
            
            for j in range(k):
                y = Xb[j,-1]
                x = Xb[j,:-1]
                if (y*(np.dot(x,w.T))) <1:
                    tempPlus = np.vstack(tempPlus,x)
                                  
            
            eta = 1/((self.lambda1) * i)
            
            # setting wt+1
            
            
            
            
            
            

In [15]:
arr = np.arange(12).reshape((4, 3))

In [16]:
np.random.shuffle(arr)


In [17]:
print(arr)

[[ 6  7  8]
 [ 0  1  2]
 [ 9 10 11]
 [ 3  4  5]]
