In [2]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


In [3]:
df = pd.read_csv("train.csv", header=None, delimiter = ',')
trainD = np.array(df)
print(trainD.shape)

(20000, 785)


In [4]:
trainX = trainD[:,:(trainD.shape[1] - 1)]
trainY = trainD[:,(trainD.shape[1]-1)]

print(trainX.shape)
print(trainY.shape)

(20000, 784)
(20000,)


In [7]:
train0 = trainD[trainD[:,-1] == 0]
train1 = trainD[trainD[:,-1] == 1]
train2 = trainD[trainD[:,-1] == 2]
train3 = trainD[trainD[:,-1] == 3]
train4 = trainD[trainD[:,-1] == 4]
train5 = trainD[trainD[:,-1] == 5]
train6 = trainD[trainD[:,-1] == 6]
train7 = trainD[trainD[:,-1] == 7]
train8 = trainD[trainD[:,-1] == 8]
train9 = trainD[trainD[:,-1] == 9]
# print(train6[0:10,:])




[[0 0 0 ... 0 0 6]
 [0 0 0 ... 0 0 6]
 [0 0 0 ... 0 0 6]
 ...
 [0 0 0 ... 0 0 6]
 [0 0 0 ... 0 0 6]
 [0 0 0 ... 0 0 6]]


In [50]:
# this class is of binary classification
class SVMbin():
    def __init__(self, x, iterations=100, lambda1 = 1):
        X=x
        self.iterations = iterations
        self.lambda1 = lambda1
        self.Y=X[:,-1]
        # here, Xb contains the 784 columns of X, and the final column is 1, for the bias term
        self.Xb = np.ones((X.shape[0],X.shape[1]))
        self.Xb[:,:-1] = X[:,:-1]
        # uniq contains the 2 unique values of X[:,-1]
        self.uniq = np.unique(X[:,-1])
        
        # def f(x):
        #     if x == self.uniq[0]:
        #         return 1
        #     else: return -1
        # 
        self.w = np.zeros((1,self.Xb.shape[1]))
        
        
    
    # assuming the final column contains the labels
    # this function will train w of dimension 1,784
    def train(self,k):
#       the first column becomes the bias layer of ones
       
        for i in range(1,self.iterations+1):
            np.random.shuffle(self.Xb)
            # temp has the first k rows of the data
            # temp = self.Xb[:k,:]
            
            # tempPlus will have all those with y<w,x> < 1
            tempPlusX = np.empty(shape=(1,self.Xb.shape[1]),dtype=int)
            tempPlusY = np.empty(shape=(1,1),dtype=int)
            for j in range(k):
                y = self.Y[j]
                x = self.Xb[j,:]
                if (y*(np.dot(x,self.w.T))) <1:
                    tempPlusX = np.vstack((tempPlusX,x))
                    tempPlusY = np.vstack((tempPlusY,y))
                    
                                  
            
            eta = 1/(self.lambda1 * i)
            
            # setting wt+1
            
            self.w = (1-eta*self.lambda1)*self.w + (eta/k)*np.sum(tempPlusY*tempPlusX)
            
        # return w
    
    #     assuming X is of dimensions (:,785)
    def predict(self,X):
        temp = np.ones((X.shape[0],X.shape[1]))
        temp[:,:-1] = X[:,:-1]
        
        def helper(t):
            td = np.dot(t,self.w.T)
            if td>0: 
                return self.uniq[0]
            else: return self.uniq[1]
        # helpervec = np.vectorize(helper())
        
        # y = helpervec(temp)
        # return y
        return np.array([helper(xi) for xi in temp])

        
    # def predict(self,data):
    #     return np.vectorize(self.predictSingle())
    #     
        
            
            
            
            

In [53]:
data01 = np.vstack((train1,train2))
# data01 = trainD[(trainD[:,-1] == 2)||(trainD[:,-1] == 1)]
# print(data01[-1,:])
trial = SVMbin(x=data01)
trial.train(k=30)
# print(data01[0:50,-1])
temptrail = data01[-50:-1,:]

print(temptrail.shape)
print(temptrail[:,-1])

print(trial.predict(temptrail))

(49, 785)
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
arr = np.arange(12).reshape((4, 3))

In [16]:
np.random.shuffle(arr)


In [17]:
print(arr)

[[ 6  7  8]
 [ 0  1  2]
 [ 9 10 11]
 [ 3  4  5]]


In [19]:
a2 = np.arange(4).reshape(4,1)
print(a2)


[[0]
 [1]
 [2]
 [3]]


In [20]:
print(a2*arr)

[[ 0  0  0]
 [ 0  1  2]
 [18 20 22]
 [ 9 12 15]]
