In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_der(x):
    return (x)*(1-(x))

In [3]:
# def neural_a(trainFile, paramFile, weightFile):
trainFile = "train.csv"
paramFile = "param.txt"

In [4]:

asArrays = pd.read_csv(trainFile,header=None).values
X = asArrays[:,:(asArrays.shape[1] - 1)]
y = asArrays[:,(asArrays.shape[1]-1)]


In [5]:

params = open(paramFile,'r')
learningRateType = int(params.readline(),10)
learningRate = float(params.readline())
maxIter = int(params.readline(),10)
batchSize = int(params.readline(),10)
nnArchitecture = params.readline().rstrip().split(' ')
nnArchitecture = list(map(int, nnArchitecture))


In [13]:
wdict = {}
zdict = {}
adict = {}
# +1 done everywhere to include bias term in the weights matrix itself
wdict[0] = np.zeros((X.shape[1] + 1,nnArchitecture[0]))

totalLayers = len(nnArchitecture)
n = X.shape[0]

for i in range(len(nnArchitecture)):
    if i!=0:
        wdict[i] = np.zeros((nnArchitecture[i-1] + 1,nnArchitecture[i]))

wdict[totalLayers] = np.zeros((nnArchitecture[totalLayers-1] + 1,1))


In [14]:

iterations = 0
while iterations<maxIter:
    iterations+=1
    
    k = ((iterations-1)*batchSize)%n
    workingX = X[k:(k+batchSize)]
    workingy = y[k:(k+batchSize)]
    
    if learningRateType==1:
        rate = learningRate
    else:
        rate = learningRate/np.sqrt(iterations)
    #forward propogation
    
    adict[-1] = np.hstack((np.ones((workingX.shape[0],1)),workingX))
    for i in range(totalLayers):
        zdict[i] = np.dot(adict[i-1],wdict[i])
        temp = sigmoid(zdict[i])
        adict[i] = np.hstack((np.ones((temp.shape[0],1)),temp))
    zdict[totalLayers] = np.dot(adict[totalLayers-1],wdict[totalLayers])
    adict[totalLayers] = sigmoid(zdict[totalLayers])
    # print(iterations)
    # print("adict[-1]")
    # print(adict[-1])
    # print("adict[0]")
    # print(adict[0])
    # print("adict[1]")
    # print(adict[1])
    


1
adict[-1]
[[ 1.00000000e+00  2.55337307e+00  1.52481329e+00]
 [ 1.00000000e+00  9.56187894e-01  1.22932837e+00]
 [ 1.00000000e+00  7.52964718e-01  3.24716693e+00]
 [ 1.00000000e+00 -9.37972128e-01  1.26415069e+00]
 [ 1.00000000e+00 -3.91551790e-01  2.39860195e+00]
 [ 1.00000000e+00  7.10285041e-01  7.27965970e-01]
 [ 1.00000000e+00 -3.63427663e+00  1.35134052e+00]
 [ 1.00000000e+00 -2.42262262e-01 -1.84743763e+00]
 [ 1.00000000e+00  2.96405404e+00 -6.85218629e-01]
 [ 1.00000000e+00 -2.83764855e+00 -1.61462203e+00]
 [ 1.00000000e+00 -9.37601418e-01  3.10300855e+00]
 [ 1.00000000e+00  1.34836311e-02 -4.25445087e-01]
 [ 1.00000000e+00 -1.10099969e+00  1.43211162e+00]
 [ 1.00000000e+00 -1.08012046e+00 -1.39912312e+00]
 [ 1.00000000e+00  4.78700086e-01  2.42931302e+00]
 [ 1.00000000e+00  1.88993082e+00  3.91197423e+00]
 [ 1.00000000e+00  2.74272207e+00  1.51959180e+00]
 [ 1.00000000e+00 -1.06199975e+00 -1.26861037e+00]
 [ 1.00000000e+00  3.04543973e+00 -1.79302512e+00]
 [ 1.00000000e+00 -